'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle2, Pause, Play, RotateCcw, Settings2 } from 'lucide-react';
type Mode='focus'|'short'|'long';
const modes:{id:Mode;label:string;minutes:number}[]=[{id:'focus',label:'집중',minutes:25},{id:'short',label:'짧은 휴식',minutes:5},{id:'long',label:'긴 휴식',minutes:15}];
export function FocusTimer(){
 const [mode,setMode]=useState<Mode>('focus'); const duration=modes.find(item=>item.id===mode)?.minutes??25;
 const [seconds,setSeconds]=useState(duration*60); const [running,setRunning]=useState(false); const [task,setTask]=useState(''); const [rounds,setRounds]=useState(0); const [syncState,setSyncState]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const intervalRef=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>()=>{if(intervalRef.current)clearInterval(intervalRef.current)},[]);
 useEffect(()=>{setSeconds(duration*60);setRunning(false);if(intervalRef.current)clearInterval(intervalRef.current)},[duration,mode]);
 async function saveSession(){setSyncState('saving');try{const response=await fetch('/api/focus-sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task,mode,durationSeconds:duration*60})});setSyncState(response.ok?'saved':'error')}catch{setSyncState('error')}}
 useEffect(()=>{if(!running){if(intervalRef.current)clearInterval(intervalRef.current);return} intervalRef.current=setInterval(()=>setSeconds(current=>{if(current<=1){setRunning(false);setRounds(value=>value+1);setSyncState('saving');void saveSession();if(intervalRef.current)clearInterval(intervalRef.current);return 0}return current-1}),1000);return()=>{if(intervalRef.current)clearInterval(intervalRef.current)}},[running,task,mode,duration]);
 const time=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`,[seconds]); const progress=1-seconds/(duration*60); const reset=()=>{setRunning(false);setSeconds(duration*60)};
 const syncText={idle:'완료된 세션은 계정에 자동 저장됩니다.',saving:'세션을 저장하는 중…',saved:'세션이 안전하게 저장됐습니다.',error:'세션을 저장하지 못했습니다.'}[syncState];
 return <section className="timer-workspace"><div className="timer-panel"><div className="mode-tabs" role="tablist" aria-label="타이머 모드">{modes.map(item=><button aria-selected={mode===item.id} className={mode===item.id?'active':''} key={item.id} onClick={()=>setMode(item.id)} role="tab" type="button">{item.label}</button>)}</div><label className="task-field"><span>이번 세션에 집중할 일</span><input maxLength={80} onChange={event=>setTask(event.target.value)} placeholder="예: 프로젝트 기획안 완성하기" value={task}/></label><div className="timer-ring" style={{'--progress':`${progress*360}deg`} as React.CSSProperties}><div><span>{mode==='focus'?'FOCUS':'BREAK'}</span><strong aria-live="polite">{time}</strong><small>{task||'집중할 일을 입력하세요'}</small></div></div><div className="timer-controls"><button aria-label="타이머 초기화" className="round-control" onClick={reset} type="button"><RotateCcw size={19}/></button><button className="play-control" onClick={()=>setRunning(value=>!value)} type="button">{running?<><Pause size={21}/> 일시정지</>:<><Play size={21}/> {seconds===0?'다시 시작':'시작'}</>}</button><button aria-label="타이머 설정" className="round-control" title="세부 설정은 다음 업데이트에서 제공됩니다" type="button"><Settings2 size={19}/></button></div></div><aside className="focus-summary"><div><p className="card-label">TODAY</p><strong>{rounds}</strong><span>완료한 세션</span></div><div className="focus-guide"><CheckCircle2 size={19}/><p><strong>한 번에 한 가지</strong><span>알림을 끄고 선택한 일에만 집중해보세요.</span></p></div><p className={`sync-note ${syncState}`} role="status">{syncText}</p></aside></section>;
}
