'use client';
import { BedDouble, Square, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { apiRequest, useApi } from '@/hooks/use-api';
import { DataNotice } from '@/components/feature-layout';
type Log={id:string;slept_at:string;woke_at:string|null;quality:number|null;note:string|null};
type SleepData={logs:Log[];activeSleep:Log|null};
const format=(value:string)=>new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(new Date(value));
export function SleepWorkspace(){
 const sleep=useApi<SleepData>('/api/sleep-logs'); const [draft,setDraft]=useState<Log|null>(null); const [quality,setQuality]=useState(''); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const active=sleep.data?.activeSleep;
 async function start(){setBusy(true);try{await apiRequest('/api/sleep-logs',{method:'POST'});await sleep.refresh()}finally{setBusy(false)}}
 async function end(){if(!active)return;setBusy(true);try{const result=await apiRequest<{log:Log}>('/api/sleep-logs',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:active.id,action:'end'})});setDraft(result.log);await sleep.refresh()}finally{setBusy(false)}}
 async function save(){if(!draft||(!quality&&!note.trim()))return;setBusy(true);try{await apiRequest<{log:Log}>('/api/sleep-logs',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:draft.id,action:'save',quality:Number(quality)||null,note})});setDraft(null);setQuality('');setNote('');await sleep.refresh()}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{await apiRequest(`/api/sleep-logs?id=${id}`,{method:'DELETE'});setDraft(null);await sleep.refresh()}finally{setBusy(false)}}
 return <div className="workspace-grid morning-grid"><section className="workspace-card sleep-card"><div className="section-title"><div><p className="card-label"><BedDouble size={16}/> 수면</p><h2>{draft?'기록 작성':active?'수면 진행 중':'오늘 밤을 준비하세요'}</h2></div></div>{draft?<div className="stack-form"><p className="sleep-intro">취침 {format(draft.slept_at)} · 기상 {format(draft.woke_at!)} · {((new Date(draft.woke_at!).getTime()-new Date(draft.slept_at).getTime())/3600000).toFixed(1)}시간</p><label><span>수면 만족도</span><select value={quality} onChange={e=>setQuality(e.target.value)}><option value="">선택 안 함</option>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}점</option>)}</select></label><label><span>메모</span><input value={note} maxLength={300} onChange={e=>setNote(e.target.value)} placeholder="오늘의 수면을 기록하세요"/></label><button className="submit-button" disabled={busy||(!quality&&!note.trim())} onClick={save}>기록 저장</button><button className="icon-button" disabled={busy} onClick={()=>remove(draft.id)}>기록 취소</button></div>:<button className="submit-button" disabled={busy} onClick={()=>active?end():start()}>{active?<><Square size={16}/>수면 종료하기</>:<><BedDouble size={16}/>수면 시작하기</>}</button>}</section><section className="workspace-card history-card"><div className="section-title"><div><p className="card-label">RECENT SLEEP</p><h2>최근 기록</h2></div></div><DataNotice loading={sleep.loading} error={sleep.error} onRetry={sleep.refresh}/><div className="record-list">{(sleep.data?.logs??[]).filter(log=>log.woke_at&&(log.quality||log.note)).map(log=><article className="record-row" key={log.id}><div><strong>{((new Date(log.woke_at!).getTime()-new Date(log.slept_at).getTime())/3600000).toFixed(1)}시간</strong><span>{format(log.slept_at)} · {format(log.woke_at!)}</span>{log.note&&<small>{log.note}</small>}</div><button className="icon-button" disabled={busy} onClick={()=>remove(log.id)}><Trash2 size={15}/></button></article>)}</div></section></div>
}
